[package]
name = "spsc"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
thiserror = "2.0.17"
tokio = {version = "1.48.0", features = ["macros", "sync", "rt-multi-thread", "time"]}
